parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     ci
    database_user:     ci
    database_password: ci

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
