security:
    encoders:
        Symfony\Component\Security\Core\User\User: md5

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_APPLICATION]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_APPLICATION, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        apps:
            entity: { class: SeiffertCiCollectorBundle:Application, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app_push_area:
            pattern:    ^/api
            http_basic:
                realm: "Authentication required"

    access_control:
        - { path: ^/api, roles: ROLE_APPLICATION }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
