parameters:
#    seiffert_ci_collector.example.class: Seiffert\CiCollectorBundle\Example

services:
#    seiffert_ci_collector.example:
#        class: %seiffert_ci_collector.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
