parameters:
    seiffert.ci_collector.command.register_app.class: Seiffert\CiCollectorBundle\Command\RegisterApplicationCommand

services:
    seiffert.ci_collector.command.register_app:
        class: %seiffert.ci_collector.command.register_app.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: console.command }
